                                                                                                                                                                                       import React from "react";
                                                                                                                                                                                       import { Search, MapPin, Globe, Building2, MousePointerClick, Camera, Satellite, Eye, EyeOff, Trash2, Plus, Settings, Save, Play, Square, Edit2, Bell } from "lucide-react";

                                                                                                                                                                                       interface Props {
                                                                                                                                                                                         onSearch: (filters: any) => void;
                                                                                                                                                                                         isLoading: boolean;
                                                                                                                                                                                       }

                                                                                                                                                                                       export default function FilterPanel({ onSearch, isLoading }: Props) {
                                                                                                                                                                                         // MODES
                                                                                                                                                                                         const [mode, setMode] = React.useState<"google" | "instagram" | "watchtower" | "settings">("google");

                                                                                                                                                                                         // Inputs
                                                                                                                                                                                         const [keyword, setKeyword] = React.useState("Jewelry Store");
                                                                                                                                                                                         const [city, setCity] = React.useState("Deira");
                                                                                                                                                                                         const [country, setCountry] = React.useState("Dubai");
                                                                                                                                                                                         const [hashtag, setHashtag] = React.useState("diamondjewelry");

                                                                                                                                                                                         // Watchtower State
                                                                                                                                                                                         const [newTag, setNewTag] = React.useState("");
                                                                                                                                                                                         const [monitoredTags, setMonitoredTags] = React.useState<string[]>([]);
                                                                                                                                                                                         const [scanning, setScanning] = React.useState(false);
                                                                                                                                                                                         const [isRunning, setIsRunning] = React.useState(false);

                                                                                                                                                                                         // Settings State
                                                                                                                                                                                         const [serpKey, setSerpKey] = React.useState("");
                                                                                                                                                                                         const [apifyKey, setApifyKey] = React.useState("");
                                                                                                                                                                                         const [discordKey, setDiscordKey] = React.useState(""); // 🆕 Discord State
                                                                                                                                                                                         const [showSerp, setShowSerp] = React.useState(false); 
                                                                                                                                                                                         const [showApify, setShowApify] = React.useState(false); 
                                                                                                                                                                                         const [isEditing, setIsEditing] = React.useState(false); 
                                                                                                                                                                                         const [savedStatus, setSavedStatus] = React.useState({ hasSerp: false, hasApify: false });

                                                                                                                                                                                         // 🔄 LOAD DATA
                                                                                                                                                                                         React.useEffect(() => {
                                                                                                                                                                                             if (mode === 'watchtower') loadWatchData();
                                                                                                                                                                                             if (mode === 'settings') loadSettings();
                                                                                                                                                                                         }, [mode]);

                                                                                                                                                                                         // ⏰ AUTO-SCANNER
                                                                                                                                                                                         React.useEffect(() => {
                                                                                                                                                                                           let interval: NodeJS.Timeout;
                                                                                                                                                                                           if (isRunning && mode === 'watchtower') {
                                                                                                                                                                                               interval = setInterval(() => { runWatchScan(false); }, 60000); 
                                                                                                                                                                                           }
                                                                                                                                                                                           return () => clearInterval(interval);
                                                                                                                                                                                         }, [isRunning, mode]);

                                                                                                                                                                                         // --- WATCHTOWER LOGIC ---
                                                                                                                                                                                         const loadWatchData = async () => {
                                                                                                                                                                                             try {
                                                                                                                                                                                               const res = await fetch('/api/monitor', { method: 'POST', body: JSON.stringify({ action: 'load' }) });
                                                                                                                                                                                               if(res.ok) {
                                                                                                                                                                                                   const data = await res.json();
                                                                                                                                                                                                   if (data.monitoredTags) setMonitoredTags(data.monitoredTags);
                                                                                                                                                                                                   if (data.leads) onSearch({ mode: 'watchtower_load', leads: data.leads });
                                                                                                                                                                                                   setIsRunning(data.isRunning);
                                                                                                                                                                                               }
                                                                                                                                                                                             } catch (e) { console.warn("Monitor API loading..."); }
                                                                                                                                                                                         };

                                                                                                                                                                                         const addWatchTag = async () => {
                                                                                                                                                                                             if(!newTag) return;
                                                                                                                                                                                             const tagClean = newTag.replace('#', '').trim();
                                                                                                                                                                                             const res = await fetch('/api/monitor', { method: 'POST', body: JSON.stringify({ action: 'add', tag: tagClean }) });
                                                                                                                                                                                             if (res.ok) { setNewTag(""); loadWatchData(); }
                                                                                                                                                                                         };

                                                                                                                                                                                         const removeWatchTag = async (tag: string) => {
                                                                                                                                                                                             await fetch('/api/monitor', { method: 'POST', body: JSON.stringify({ action: 'remove', tag }) });
                                                                                                                                                                                             loadWatchData();
                                                                                                                                                                                         };

                                                                                                                                                                                         const toggleMonitor = async () => {
                                                                                                                                                                                             const action = isRunning ? "stop" : "start";
                                                                                                                                                                                             await fetch('/api/monitor', { method: 'POST', body: JSON.stringify({ action }) });
                                                                                                                                                                                             setIsRunning(!isRunning);
                                                                                                                                                                                         };

                                                                                                                                                                                         const runWatchScan = async (force: boolean) => {
                                                                                                                                                                                             setScanning(true);
                                                                                                                                                                                             try {
                                                                                                                                                                                                 const res = await fetch('/api/monitor', { method: 'POST', body: JSON.stringify({ action: 'scan', force }) });

                                                                                                                                                                                                 if (!res.ok) {
                                                                                                                                                                                                     const text = await res.text();
                                                                                                                                                                                                     throw new Error(`Server Error (${res.status}): ${text}`);
                                                                                                                                                                                                 }

                                                                                                                                                                                                 const data = await res.json();

                                                                                                                                                                                                 if (force) {
                                                                                                                                                                                                     if (data.error) alert("❌ Error: " + data.error);
                                                                                                                                                                                                     else alert(`✅ Scan Complete! Found ${data.newLeads} new leads.`);
                                                                                                                                                                                                 }
                                                                                                                                                                                                 if (data.newLeads > 0 || force) loadWatchData(); 
                                                                                                                                                                                             } catch(e: any) {
                                                                                                                                                                                                 if(force) alert("❌ SYSTEM FAIL: " + e.message);
                                                                                                                                                                                             } finally {
                                                                                                                                                                                                 setScanning(false);
                                                                                                                                                                                             }
                                                                                                                                                                                         };

                                                                                                                                                                                         // --- SETTINGS LOGIC ---
                                                                                                                                                                                         const loadSettings = async () => {
                                                                                                                                                                                             try {
                                                                                                                                                                                                 const res = await fetch('/api/settings');
                                                                                                                                                                                                 if (res.ok) {
                                                                                                                                                                                                     const data = await res.json();
                                                                                                                                                                                                     setSerpKey(data.serpapi_key || "");
                                                                                                                                                                                                     setApifyKey(data.apify_token || "");
                                                                                                                                                                                                     setDiscordKey(data.discord_webhook || ""); // Load Discord
                                                                                                                                                                                                     setSavedStatus({ hasSerp: !!data.serpapi_key, hasApify: !!data.apify_token });
                                                                                                                                                                                                 }
                                                                                                                                                                                             } catch (e) { console.warn("Settings loading..."); }
                                                                                                                                                                                         };

                                                                                                                                                                                         const saveSettings = async () => {
                                                                                                                                                                                             try {
                                                                                                                                                                                                 const res = await fetch('/api/settings', {
                                                                                                                                                                                                     method: 'POST',
                                                                                                                                                                                                     body: JSON.stringify({ 
                                                                                                                                                                                                         serpapi_key: serpKey, 
                                                                                                                                                                                                         apify_token: apifyKey,
                                                                                                                                                                                                         discord_webhook: discordKey // Save Discord
                                                                                                                                                                                                     })
                                                                                                                                                                                                 });
                                                                                                                                                                                                 if(res.ok) {
                                                                                                                                                                                                     alert("✅ Keys Saved & Secured!");
                                                                                                                                                                                                     setIsEditing(false); 
                                                                                                                                                                                                     loadSettings();
                                                                                                                                                                                                 } else { alert("Failed to save keys."); }
                                                                                                                                                                                             } catch(e) { alert("Error connecting to settings API."); }
                                                                                                                                                                                         };

                                                                                                                                                                                         const handleSearch = () => { onSearch({ mode, keyword, city, country, hashtag }); };

                                                                                                                                                                                         // Shortcuts
                                                                                                                                                                                         const GOOGLE_HOTSPOTS = [
                                                                                                                                                                                           { label: "🇦🇪 Dubai Gold Souq", c: "Deira", co: "Dubai" },
                                                                                                                                                                                           { label: "🇯🇵 Tokyo Diamond Dist.", c: "Okachimachi", co: "Japan" },
                                                                                                                                                                                           { label: "🇺🇸 NYC Diamond Dist.", c: "New York", co: "USA" },
                                                                                                                                                                                         ];

                                                                                                                                                                                         return (
                                                                                                                                                                                           <div className="bg-white border-r border-slate-200 p-6 flex flex-col h-full w-full md:w-80 shrink-0 shadow-xl z-20 overflow-y-auto">

                                                                                                                                                                                             {/* MODE TABS */}
                                                                                                                                                                                             <div className="flex bg-slate-100 p-1 rounded-lg mb-8 gap-1">
                                                                                                                                                                                               <button onClick={() => setMode("google")} className={`flex-1 py-2 rounded transition-all ${mode === "google" ? "bg-white shadow" : "text-slate-400"}`}><Satellite className="w-4 h-4 mx-auto" /></button>
                                                                                                                                                                                               <button onClick={() => setMode("instagram")} className={`flex-1 py-2 rounded transition-all ${mode === "instagram" ? "bg-white shadow text-pink-500" : "text-slate-400"}`}><Camera className="w-4 h-4 mx-auto" /></button>
                                                                                                                                                                                               <button onClick={() => setMode("watchtower")} className={`flex-1 py-2 rounded transition-all ${mode === "watchtower" ? "bg-slate-900 shadow text-emerald-400" : "text-slate-400"}`}><Eye className="w-4 h-4 mx-auto" /></button>
                                                                                                                                                                                               <button onClick={() => setMode("settings")} className={`flex-1 py-2 rounded transition-all ${mode === "settings" ? "bg-white shadow text-slate-800" : "text-slate-400"}`}><Settings className="w-4 h-4 mx-auto" /></button>
                                                                                                                                                                                             </div>

                                                                                                                                                                                             {/* ⚙️ SETTINGS MODE */}
                                                                                                                                                                                             {mode === "settings" && (
                                                                                                                                                                                               <div className="animate-slide-in space-y-6">
                                                                                                                                                                                                   <h3 className="text-slate-900 font-bold text-lg mb-4 flex justify-between items-center">
                                                                                                                                                                                                       API Configuration
                                                                                                                                                                                                       {!isEditing && (
                                                                                                                                                                                                           <button onClick={() => setIsEditing(true)} className="text-xs bg-slate-100 px-3 py-1 rounded text-slate-600 flex items-center gap-1 hover:bg-slate-200">
                                                                                                                                                                                                               <Edit2 className="w-3 h-3"/> Edit
                                                                                                                                                                                                           </button>
                                                                                                                                                                                                       )}
                                                                                                                                                                                                   </h3>

                                                                                                                                                                                                   {/* SERP API */}
                                                                                                                                                                                                   <div className="p-4 border rounded-lg bg-slate-50 transition-colors focus-within:border-slate-400">
                                                                                                                                                                                                       <label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Google Maps Key</label>
                                                                                                                                                                                                       <div className="relative">
                                                                                                                                                                                                           <input type={showSerp ? "text" : "password"} className="w-full bg-white border border-slate-300 rounded p-2 pr-10 text-sm font-mono text-slate-700 outline-none focus:ring-1 focus:ring-slate-400" placeholder={isEditing ? "Paste key here..." : "Key Saved"} value={serpKey} onChange={(e) => setSerpKey(e.target.value)} disabled={!isEditing} />
                                                                                                                                                                                                           <button onClick={() => setShowSerp(!showSerp)} className="absolute right-3 top-2.5 text-slate-400 hover:text-slate-600">{showSerp ? <EyeOff className="w-4 h-4"/> : <Eye className="w-4 h-4"/>}</button>
                                                                                                                                                                                                       </div>
                                                                                                                                                                                                   </div>

                                                                                                                                                                                                   {/* APIFY */}
                                                                                                                                                                                                   <div className="p-4 border rounded-lg bg-slate-50 transition-colors focus-within:border-slate-400">
                                                                                                                                                                                                       <label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Instagram Token</label>
                                                                                                                                                                                                       <div className="relative">
                                                                                                                                                                                                           <input type={showApify ? "text" : "password"} className="w-full bg-white border border-slate-300 rounded p-2 pr-10 text-sm font-mono text-slate-700 outline-none focus:ring-1 focus:ring-slate-400" placeholder={isEditing ? "Paste token here..." : "Token Saved"} value={apifyKey} onChange={(e) => setApifyKey(e.target.value)} disabled={!isEditing} />
                                                                                                                                                                                                           <button onClick={() => setShowApify(!showApify)} className="absolute right-3 top-2.5 text-slate-400 hover:text-slate-600">{showApify ? <EyeOff className="w-4 h-4"/> : <Eye className="w-4 h-4"/>}</button>
                                                                                                                                                                                                       </div>
                                                                                                                                                                                                   </div>

                                                                                                                                                                                                   {/* DISCORD WEBHOOK */}
                                                                                                                                                                                                   <div className="p-4 border rounded-lg bg-slate-50 transition-colors focus-within:border-slate-400">
                                                                                                                                                                                                       <label className="text-xs font-bold text-slate-500 uppercase mb-2 flex items-center gap-2">
                                                                                                                                                                                                           <Bell className="w-3 h-3" /> Discord Webhook URL
                                                                                                                                                                                                       </label>
                                                                                                                                                                                                       <input 
                                                                                                                                                                                                           type="text" 
                                                                                                                                                                                                           className="w-full bg-white border border-slate-300 rounded p-2 text-sm font-mono text-slate-700 outline-none focus:ring-1 focus:ring-slate-400"
                                                                                                                                                                                                           placeholder="https://discord.com/api/webhooks/..."
                                                                                                                                                                                                           value={discordKey} 
                                                                                                                                                                                                           onChange={(e) => setDiscordKey(e.target.value)}
                                                                                                                                                                                                           disabled={!isEditing}
                                                                                                                                                                                                       />
                                                                                                                                                                                                       <p className="text-[10px] text-slate-400 mt-2">Leads will be sent here instantly.</p>
                                                                                                                                                                                                   </div>

                                                                                                                                                                                                   {isEditing && (
                                                                                                                                                                                                       <button onClick={saveSettings} className="w-full bg-slate-900 text-white font-bold py-4 rounded-lg shadow-lg text-sm flex justify-center items-center gap-2 mt-auto hover:bg-slate-800 transition-colors">
                                                                                                                                                                                                           <Save className="w-4 h-4" /> SAVE CHANGES
                                                                                                                                                                                                       </button>
                                                                                                                                                                                                   )}
                                                                                                                                                                                               </div>
                                                                                                                                                                                             )}

                                                                                                                                                                                             {/* GOOGLE MODE */}
                                                                                                                                                                                             {mode === "google" && (
                                                                                                                                                                                               <div className="animate-slide-in space-y-6">
                                                                                                                                                                                                    <div><label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Target Business</label><input type="text" className="w-full bg-slate-50 border border-slate-300 rounded p-3 text-sm" value={keyword} onChange={(e) => setKeyword(e.target.value)} /></div>
                                                                                                                                                                                                   <div><label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Location</label><input type="text" className="w-full bg-slate-50 border border-slate-300 rounded p-3 mb-2 text-sm" value={city} onChange={(e) => setCity(e.target.value)} placeholder="City" /><input type="text" className="w-full bg-slate-50 border border-slate-300 rounded p-3 text-sm" value={country} onChange={(e) => setCountry(e.target.value)} placeholder="Country" /></div>
                                                                                                                                                                                                   <div className="mb-4"><label className="text-xs font-bold text-slate-400 uppercase mb-2 flex items-center gap-2"><MousePointerClick className="w-3 h-3" /> Quick Select</label><div className="grid grid-cols-1 gap-2">{GOOGLE_HOTSPOTS.map((spot) => (<button key={spot.label} onClick={() => { setCity(spot.c); setCountry(spot.co); }} className="text-left text-xs px-3 py-2 bg-slate-50 hover:bg-slate-100 border border-slate-200 rounded text-slate-600 transition-colors">{spot.label}</button>))}</div></div>
                                                                                                                                                                                                   <button onClick={handleSearch} disabled={isLoading} className="w-full bg-slate-900 text-white font-bold py-4 rounded-lg shadow-lg text-sm flex justify-center items-center gap-2">{isLoading ? "Scanning..." : "FIND REAL LEADS"}</button>
                                                                                                                                                                                               </div>
                                                                                                                                                                                             )}

                                                                                                                                                                                             {/* INSTAGRAM MODE */}
                                                                                                                                                                                             {mode === "instagram" && (
                                                                                                                                                                                               <div className="animate-slide-in space-y-6">
                                                                                                                                                                                                   <div><label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Target Hashtags</label><input type="text" className="w-full bg-slate-50 border border-slate-300 rounded p-3 text-sm" value={hashtag} onChange={(e) => setHashtag(e.target.value)} /><p className="text-[10px] text-slate-400 mt-1">Separate multiple tags with commas.</p></div>
                                                                                                                                                                                                   <button onClick={handleSearch} disabled={isLoading} className="w-full bg-gradient-to-r from-purple-500 to-pink-500 text-white font-bold py-4 rounded-lg shadow-lg text-sm flex justify-center items-center gap-2">{isLoading ? "Scanning..." : "SCAN INSTAGRAM"}</button>
                                                                                                                                                                                               </div>
                                                                                                                                                                                             )}

                                                                                                                                                                                             {/* WATCHTOWER MODE */}
                                                                                                                                                                                             {mode === "watchtower" && (
                                                                                                                                                                                               <div className="animate-slide-in space-y-6">
                                                                                                                                                                                                   <div className={`p-4 border rounded-lg transition-colors ${isRunning ? "bg-emerald-50 border-emerald-200" : "bg-slate-50 border-slate-200"}`}><div className="flex justify-between items-center mb-2"><h3 className={`font-bold text-sm flex items-center gap-2 ${isRunning ? "text-emerald-800" : "text-slate-500"}`}><Eye className={`w-4 h-4 ${isRunning ? "animate-pulse" : ""}`}/> {isRunning ? "MONITOR ACTIVE" : "MONITOR PAUSED"}</h3><div className={`w-2 h-2 rounded-full ${isRunning ? "bg-emerald-500 animate-ping" : "bg-slate-300"}`} /></div><p className="text-[10px] text-slate-500">{isRunning ? "Auto-scanning every 60s for NEW posts." : "System is idle."}</p></div>
                                                                                                                                                                                                   <div className="flex gap-2">{!isRunning ? (<button onClick={toggleMonitor} className="flex-1 bg-emerald-600 hover:bg-emerald-700 text-white font-bold py-3 rounded-lg shadow text-sm flex justify-center items-center gap-2"><Play className="w-4 h-4 fill-white" /> START</button>) : (<button onClick={toggleMonitor} className="flex-1 bg-slate-200 hover:bg-slate-300 text-slate-700 font-bold py-3 rounded-lg shadow-inner text-sm flex justify-center items-center gap-2"><Square className="w-4 h-4 fill-slate-700" /> STOP</button>)}</div>
                                                                                                                                                                                                   <div className="pt-4 border-t border-slate-100"><label className="text-xs font-bold text-slate-500 uppercase mb-2 block">Add Tag</label><div className="flex gap-2"><input type="text" className="flex-1 bg-slate-50 border border-slate-300 rounded p-2 text-sm" placeholder="#diamond" value={newTag} onChange={(e) => setNewTag(e.target.value)} /><button onClick={addWatchTag} className="bg-slate-900 text-white p-2 rounded hover:bg-slate-700"><Plus className="w-4 h-4" /></button></div></div>
                                                                                                                                                                                                   <div className="space-y-2"><label className="text-xs font-bold text-slate-500 uppercase block">Active Monitors</label>{monitoredTags.length === 0 && <p className="text-xs text-slate-400 italic">No active monitors.</p>}{monitoredTags.map(tag => (<div key={tag} className="flex justify-between items-center bg-white border p-3 rounded shadow-sm"><span className="font-bold text-slate-700">#{tag}</span><button onClick={() => removeWatchTag(tag)} className="text-red-400 hover:text-red-600"><Trash2 className="w-4 h-4" /></button></div>))}</div>
                                                                                                                                                                                                   <button onClick={() => runWatchScan(true)} disabled={scanning} className="w-full border border-slate-300 text-slate-500 font-bold py-2 rounded text-xs mt-auto hover:bg-slate-50 transition-colors">{scanning ? "Checking..." : "Run Manual Check Once"}</button>
                                                                                                                                                                                               </div>
                                                                                                                                                                                             )}
                                                                                                                                                                                           </div>
                                                                                                                                                                                         );
                                                                                                                                                                                       }